apiVersion: v1
entries:
  liferay:
    - apiVersion: v2
      appVersion: latest
      created: "2025-01-24T22:52:18.19420728Z"
      description: A Liferay DXP Helm chart for Kubernetes
      digest: b5d16bf7c3c38a5e0bd30d93550e857eef78e55e077fd04e06c69a122f1c302a
      name: liferay
      type: application
      urls:
        - oci://ghcr.io/liferaycloud/liferay-helm-chart/charts/liferay:0.1.8
      version: 0.1.8
    - apiVersion: v2
      appVersion: latest
      created: "2025-01-21T17:22:22.652486908Z"
      description: A Liferay DXP Helm chart for Kubernetes
      digest: 3c3b863da7e35a41d8ae0d199415505ba1bcd4719baf2d3cb4556b764fcc1bc8
      name: liferay
      type: application
      urls:
        - oci://ghcr.io/liferaycloud/liferay-helm-chart/charts/liferay:0.1.5
      version: 0.1.5
generated: "2025-01-24T22:52:18.192194209Z"
