{{- if .Values.search.internal.enabled }}
{{- with .Values.search }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "liferay.fullname" $ }}-search
  namespace: {{ include "liferay.namespace" . | quote }}
  labels:
    app: {{ $.Chart.Name }}-search
    {{- include "liferay.labels" $ | nindent 4 }}
spec:
  replicas: {{ .internal.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-search
      {{- include "liferay.selectorLabels" $ | nindent 6 }}
  serviceName: {{ include "liferay.fullname" $ }}-search
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}-search
        {{- include "liferay.labels" $ | nindent 8 }}
    spec:
      {{- with .internal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $.Chart.Name }}-search
        env:
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.transport.ssl.enabled
          value: "false"
        - name: xpack.security.http.ssl.enabled
          value: "false"
        - name: cluster.name
          value: {{ .config.clusterName }}
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: ELASTIC_PASSWORD
          value: {{ .config.password }}
        {{- with .internal.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image:  {{ printf "%s:%s" (default "search" .internal.image.repository) ((default "8.17.0" .internal.image.tag) | toString) }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- with .internal.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: search
          containerPort: {{ default "9200" .config.port }}
          protocol: TCP
        {{- with .internal.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .internal.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .internal.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config
          name: {{ include "liferay.fullname" $ }}-search-pvc
          subPath: config
        - mountPath: /usr/share/elasticsearch/data
          name: {{ include "liferay.fullname" $ }}-search-pvc
          subPath: data
        - mountPath: /usr/share/elasticsearch/logs
          name: {{ include "liferay.fullname" $ }}-search-pvc
          subPath: logs
        - mountPath: /usr/share/elasticsearch/plugins
          name: {{ include "liferay.fullname" $ }}-search-pvc
          subPath: plugins
      {{- with .internal.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      - name: install-plugins
        image:  {{ printf "%s:%s" (default "search" .internal.image.repository) ((default "8.17.0" .internal.image.tag) | toString) }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command:
        - 'sh'
        - '-c'
        - |
          if [ ! -d ./plugins/analysis-icu ];then
            bin/elasticsearch-plugin install --batch analysis-icu analysis-kuromoji analysis-smartcn analysis-stempel
          else
            echo "Plugins already installed!"
          fi

          if [ ! -e ./_config/log4j2.properties ];then
            cp -rv ./config/* ./_config
          fi

          find . -mtime -1 -ls
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/plugins
          name: {{ include "liferay.fullname" $ }}-search-pvc
          subPath: plugins
        - mountPath: /usr/share/elasticsearch/_config
          name: {{ include "liferay.fullname" $ }}-search-pvc
          subPath: config
      {{- with .internal.initContainers -}}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- with .internal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .internal.schedulingGates }}
      schedulingGates:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ include "liferay.serviceAccountName" $ }}
      {{- with .internal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: {{ include "liferay.fullname" $ }}-search-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ default "1Gi" .internal.storage}}
      {{- if .internal.storageClassName }}
      storageClassName: {{ .internal.storageClassName }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "liferay.fullname" $ }}-search
  namespace: {{ include "liferay.namespace" . | quote }}
  labels:
    app: {{ $.Chart.Name }}-search
    {{- include "liferay.labels" $ | nindent 4 }}
spec:
  selector:
    app: {{ $.Chart.Name }}-search
    {{- include "liferay.selectorLabels" $ | nindent 4 }}
  ports:
  - name: search
    port: {{ .config.port }}
    targetPort: search
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "liferay.fullname" $ }}-search-headless
  namespace: {{ include "liferay.namespace" . | quote }}
  labels:
    app: {{ $.Chart.Name }}-search
    {{- include "liferay.labels" $ | nindent 4 }}
spec:
  clusterIP: None # This is what makes it headless
  selector:
    app: {{ $.Chart.Name }}-search
    {{- include "liferay.selectorLabels" $ | nindent 4 }}
  ports:
  - name: search
    port: {{ .config.port }}
    targetPort: search
    protocol: TCP
{{- end }}
{{- end }}
