mutation (
  $githubRepository: String!
  $branchName: String!
  $expectedHeadOid: GitObjectID!
  $commitMessage: String!
  $additions: [FileAddition]
  $deletions: [FileDeletion]
) {
  createCommitOnBranch(
    input: {
      branch: {
        repositoryNameWithOwner: $githubRepository
        branchName: $branchName
      }
      message: { headline: $commitMessage }
      fileChanges: { additions: $additions, deletions: $deletions }
      expectedHeadOid: $expectedHeadOid
    }
  ) {
    commit {
      url
    }
  }
}
