apiVersion: v1
kind: Service
metadata:
  name: {{ include "liferay.fullname" . }}-headless
  namespace: {{ include "liferay.namespace" . | quote }}
  labels:
    app: {{ $.Chart.Name }}
    {{- include "liferay.labels" . | nindent 4 }}
spec:
  clusterIP: None # This is what makes it headless
  ports:
    - port: {{ .Values.service.clusterPort }}
      targetPort: cluster
      protocol: TCP
      name: cluster
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $.Chart.Name }}
    {{- include "liferay.selectorLabels" . | nindent 4 }}
